apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./.infra/k8s/*
      - ./.infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: rama89/ticketing_auth_service
      context: microservices-express/auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: rama89/ticketing_tickets_service
      context: microservices-express/tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: rama89/ticketing_orders_service
      context: microservices-express/orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: rama89/ticketing_expiration_service
      context: microservices-express/expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: rama89/ticketing_payments_service
      context: microservices-express/payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: rama89/ticketing_web_client
      context: client-next
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
