name: tests-payments

on:
  pull_request:
    paths:
      - 'microservices-express/payments/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd microservices-express/payments && yarn install && yarn test:ci
