name: tests-tickets

on:
  pull_request:
    paths:
      - 'microservices-express/tickets/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd microservices-express/tickets && yarn install && yarn test:ci
